"""migration 4

Revision ID: 6c538c66b9e0
Revises: 13141bf6ef22
Create Date: 2025-01-30 13:25:55.868011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c538c66b9e0'
down_revision: Union[str, None] = '13141bf6ef22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('beg_hour', sa.Integer(), nullable=True),
    sa.Column('beg_min', sa.Integer(), nullable=True),
    sa.Column('end_hour', sa.Integer(), nullable=True),
    sa.Column('end_min', sa.Integer(), nullable=True),
    sa.Column('confirm', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_room_id'), 'booking', ['room_id'], unique=False)
    op.create_index(op.f('ix_booking_user_id'), 'booking', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_user_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_room_id'), table_name='booking')
    op.drop_table('booking')
    # ### end Alembic commands ###
