"""migration 1

Revision ID: abbfcac6be53
Revises: 70bd0a300922
Create Date: 2025-01-26 23:41:46.300894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abbfcac6be53'
down_revision: Union[str, None] = '70bd0a300922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access_token')
    # ### end Alembic commands ###
