# Generated by Django 5.1.4 on 2025-01-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('beg_hour', models.IntegerField()),
                ('beg_min', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('end_min', models.IntegerField()),
                ('confirm', models.BooleanField()),
                ('room', models.ManyToManyField(related_name='rooms', to='bookapp.room')),
            ],
        ),
    ]
