# Generated by Django 5.1.4 on 2025-01-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('date', models.DateField()),
                ('beg_hour', models.IntegerField()),
                ('beg_min', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('end_min', models.IntegerField()),
                ('confirm', models.BooleanField()),
            ],
        ),
    ]
