# Generated by Django 5.1.4 on 2025-01-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
