# Generated by Django 5.1.4 on 2025-01-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_alter_booking_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_id',
            new_name='room',
        ),
    ]
